from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from auth.domain.entities import OAuthAccount, RefreshToken, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> None: ...


class OAuthAccountRepository(Protocol):
    async def get_by_provider(self, provider: str, provider_user_id: str) -> OAuthAccount | None: ...
    async def save(self, account: OAuthAccount) -> None: ...


class RefreshTokenRepository(Protocol):
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def save(self, token: RefreshToken) -> None: ...
    async def revoke(self, token_id: UUID, revoked_at: datetime) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID, revoked_at: datetime) -> None: ...
