from __future__ import annotations

from typing import Protocol
from uuid import UUID

from resume.domain.entities import (
    Education,
    Project,
    Resume,
    ResumeSkillEntry,
    Skill,
    SkillCategory,
    Technology,
    WorkExperience,
    WorkExperienceBullet,
)


class ResumeRepository(Protocol):
    async def get_by_id(self, resume_id: UUID) -> Resume | None: ...
    async def get_active_for_user(self, user_id: UUID) -> Resume | None: ...
    async def list_by_user(self, user_id: UUID) -> list[Resume]: ...
    async def save(self, resume: Resume) -> None: ...
    async def delete(self, resume_id: UUID) -> None: ...
    async def deactivate_all_for_user(self, user_id: UUID) -> None: ...


class WorkExperienceRepository(Protocol):
    async def get_by_id(self, experience_id: UUID) -> WorkExperience | None: ...
    async def list_by_resume(self, resume_id: UUID) -> list[WorkExperience]: ...
    async def save(self, experience: WorkExperience) -> None: ...
    async def save_bullets(self, experience_id: UUID, bullets: list[WorkExperienceBullet]) -> None: ...
    async def delete(self, experience_id: UUID) -> None: ...
    async def update_sort_orders(self, items: list[tuple[UUID, int]]) -> None: ...


class EducationRepository(Protocol):
    async def get_by_id(self, education_id: UUID) -> Education | None: ...
    async def list_by_resume(self, resume_id: UUID) -> list[Education]: ...
    async def save(self, education: Education) -> None: ...
    async def delete(self, education_id: UUID) -> None: ...


class ProjectRepository(Protocol):
    async def get_by_id(self, project_id: UUID) -> Project | None: ...
    async def list_by_resume(self, resume_id: UUID) -> list[Project]: ...
    async def save(self, project: Project) -> None: ...
    async def save_technologies(self, project_id: UUID, technology_ids: list[tuple[UUID, int]]) -> None: ...
    async def delete(self, project_id: UUID) -> None: ...
    async def update_sort_orders(self, items: list[tuple[UUID, int]]) -> None: ...


class SkillRepository(Protocol):
    async def list_all(self) -> list[Skill]: ...
    async def list_categories(self) -> list[SkillCategory]: ...
    async def get_resume_skills(self, resume_id: UUID) -> list[ResumeSkillEntry]: ...
    async def set_resume_skills(self, resume_id: UUID, entries: list[ResumeSkillEntry]) -> None: ...
    async def list_technologies(self) -> list[Technology]: ...
