from __future__ import annotations

from typing import Protocol
from uuid import UUID

from bucket_list.domain.entities import (
    BucketListItem,
    BucketListStatus,
    Destination,
    DestinationCategory,
    Visit,
)


class DestinationRepository(Protocol):
    async def get_by_id(self, destination_id: UUID) -> Destination | None: ...
    async def list_all(
        self,
        category_id: UUID | None = None,
        country: str | None = None,
        continent: str | None = None,
    ) -> list[Destination]: ...
    async def save(self, destination: Destination) -> None: ...
    async def delete(self, destination_id: UUID) -> None: ...


class BucketListItemRepository(Protocol):
    async def get_by_id(self, item_id: UUID) -> BucketListItem | None: ...
    async def get_by_user_and_destination(
        self, user_id: UUID, destination_id: UUID
    ) -> BucketListItem | None: ...
    async def list_by_user(self, user_id: UUID) -> list[BucketListItem]: ...
    async def save(self, item: BucketListItem) -> None: ...
    async def delete(self, item_id: UUID) -> None: ...


class VisitRepository(Protocol):
    async def get_by_id(self, visit_id: UUID) -> Visit | None: ...
    async def list_by_user(self, user_id: UUID) -> list[Visit]: ...
    async def save(self, visit: Visit) -> None: ...
    async def delete(self, visit_id: UUID) -> None: ...


class StatusRepository(Protocol):
    async def list_statuses(self) -> list[BucketListStatus]: ...
    async def get_status_by_id(self, status_id: UUID) -> BucketListStatus | None: ...
    async def list_categories(self) -> list[DestinationCategory]: ...
