from typing import Protocol
from uuid import UUID

from blog.domain.entities import Post, PostStatus, Tag


class PostRepository(Protocol):
    async def get_by_id(self, post_id: UUID) -> Post | None: ...
    async def get_by_slug(self, slug: str) -> Post | None: ...
    async def list_all(
            self,
            status_id: UUID | None = None,
            author_id: UUID | None = None,
    ) -> list[Post]: ...
    async def save(self, post: Post) -> None: ...
    async def set_tags(self, post_id: UUID, tag_ids: list[UUID]) -> None: ...
    async def delete(self, post_id: UUID) -> None: ...


class TagRepository(Protocol):
    async def get_by_id(self, tag_id: UUID) -> Tag | None: ...
    async def list_all(self) -> list[Tag]: ...


class StatusRepository(Protocol):
    async def list_statuses(self) -> list[PostStatus]: ...
    async def get_by_status_id(self, status_id: UUID) -> PostStatus | None: ...
